# Generated by Django 4.0.5 on 2022-06-28 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peripheral_manager', '0003_cadastroproduto_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroproduto',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cadastroproduto',
            old_name='nomeProduto',
            new_name='nameProduct',
        ),
        migrations.RenameField(
            model_name='cadastroproduto',
            old_name='tipo',
            new_name='typeProduct',
        ),
        migrations.AlterField(
            model_name='cadastroproduto',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por Field:'),
        ),
    ]
