# Generated by Django 4.0.5 on 2022-06-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peripheral_manager', '0004_rename_descricao_cadastroproduto_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroproduto',
            old_name='autor',
            new_name='author',
        ),
    ]
