# Generated by Django 4.0.5 on 2022-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripheral_manager', '0005_rename_autor_cadastroproduto_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
