# Generated by Django 4.0.5 on 2022-06-29 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peripheral_manager', '0006_cadastroequipamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroequipamento',
            options={'verbose_name': 'Estoque'},
        ),
        migrations.RemoveField(
            model_name='cadastroproduto',
            name='author',
        ),
        migrations.AddField(
            model_name='cadastroequipamento',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroequipamento',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='peripheral_manager.cadastroproduto', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroequipamento',
            name='heritage',
            field=models.CharField(default=1, max_length=12, verbose_name='Patrimônio:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroequipamento',
            name='ticket',
            field=models.CharField(default=1, max_length=250, verbose_name='N° do Chamado:'),
            preserve_default=False,
        ),
    ]
